spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog?serverTimezone=UTC&useUnicode=true
    username: root
    password: 231114
  redis:
    host: 192.168.91.130
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0


logging:
  level:
    root: info
    com.ny: debug
  file:
    path: log/blog-dev.log

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ny.po
  configuration:
    map-underscore-to-camel-case: true
